name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 150
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - 'nightly'
        group: [ 'short', 'long' ]
        os:
          - ubuntu-latest
        memlimit: [ '2', '2.5', '3', '3.5', '4', '4.5', '5.0', '5.5', '6', '6.5', '7', '0']

    steps:
      - uses: actions/checkout@v3
        with:
          # For Codecov, we must also fetch the parent of the HEAD commit to
          # be able to properly deal with PRs / merges
          fetch-depth: 2
      - name: "Install custom julia"
        uses: julia-actions/install-julia-from-url@main
        with:
          url: 'https://buildkite.com/organizations/julialang/pipelines/julia-release-1-dot-10/builds/88/jobs/018b3b0d-777a-4db5-b85a-9fd2eb4248ed/artifacts/018b3b16-7d36-4914-aea7-87e5962f6f94'
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1
      - name: "workaround..."
        run: sed -i -e 's/""" module/"""\nmodule/g' /home/runner/.julia/packages/GAP/*/src/GAP.jl
      - name: "limit OpenMP threads"
        run: echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV
      - name: "set memory limit"
        if: matrix.memlimit != '0'
        run: echo "OSCARCI_MAX_MEM_GB=${{ matrix.memlimit }}" >> $GITHUB_ENV
      - name: "set test subgroup"
        if: ${{ matrix.group }} != ''
        run: echo "OSCAR_TEST_SUBSET=${{matrix.group}}" >> $GITHUB_ENV
      - name: "Run tests"
        uses: julia-actions/julia-runtest@latest
        with:
          annotate: ${{ matrix.julia-version == '1.9' }}
          depwarn: error

