name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 150
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '~1.10.0-0'
          - 'nightly'
        os:
          - ubuntu-latest
        memlimit: [ '2', '2.5', '3', '3.5', '4', '4.5', '5.0', '5.5', '6']
        include:
          - julia-version: 'nightly'
            os: macOS-latest
            memlimit: 8
          - julia-version: 'nightly'
            os: macOS-latest
            memlimit: 11

    steps:
      - uses: actions/checkout@v3
        with:
          # For Codecov, we must also fetch the parent of the HEAD commit to
          # be able to properly deal with PRs / merges
          fetch-depth: 2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1
      - name: "limit OpenMP threads"
        run: echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV
      - name: "set memory limit"
        run: echo "OSCARCI_MAX_MEM_GB=${{ matrix.memlimit }}" >> $GITHUB_ENV
      - name: "Run tests"
        uses: julia-actions/julia-runtest@latest
        with:
          annotate: ${{ matrix.julia-version == '1.9' }}
          depwarn: error

